FROM ${NS_REMOTE}/dns-centos-systemd:${VERSION}.${CONTAINER_BRANCH}

MAINTAINER Operations at Ribose <operations@ribose.com>

LABEL description "Simple DNS authoritative server with DNSSEC support" \
      maintainer="Hardware <contact@meshup.net>"

ARG NSD_VERSION=4.1.17

# https://pgp.mit.edu/pks/lookup?search=0x7E045F8D&fingerprint=on&op=index
# pub  4096R/7E045F8D 2011-04-21 W.C.A. Wijngaards <wouter@nlnetlabs.nl>
ARG GPG_SHORTID="0x7E045F8D"
ARG GPG_FINGERPRINT="EDFA A3F2 CA4E 6EB0 5681  AF8E 9F6F 1C2D 7E04 5F8D"
ARG SHA256_HASH="107fa506d18ed6fd0a922d1b96774afd9270ec38ec6b17cd7c46fb9433a03a6c"

ENV UID=991 GID=991

RUN yum install -y openssl openssl-devel
# TODO: upgrade nsd package - this is old
RUN yum install http://share.lucidsolutions.co.nz/pub/centos/nsd/nsd-4.1.6-3.el7.centos.x86_64.rpm
RUN yum install -y nsd

# Run the setup script to create self signed certificates for controlling NSD (iff the nsd-control support is enabled) and for the server itself.
RUN nsd-control-setup

# Start the service.
RUN systemctl enable nsd
# RUN systemctl start nsd

# RUN cd /tmp \
#  && wget -q https://www.nlnetlabs.nl/downloads/nsd/nsd-${NSD_VERSION}.tar.gz \
#  && wget -q https://www.nlnetlabs.nl/downloads/nsd/nsd-${NSD_VERSION}.tar.gz.asc \
#  && echo "Verifying both integrity and authenticity of nsd-${NSD_VERSION}.tar.gz..." \
#  && CHECKSUM=$(sha256sum nsd-${NSD_VERSION}.tar.gz | awk '{print $1}') \
#  && if [ "${CHECKSUM}" != "${SHA256_HASH}" ]; then echo "Warning! Checksum does not match!" && exit 1; fi \
#  && gpg --keyserver keys.gnupg.net --recv-keys ${GPG_SHORTID} \
#  && FINGERPRINT="$(LANG=C gpg --verify nsd-${NSD_VERSION}.tar.gz.asc nsd-${NSD_VERSION}.tar.gz 2>&1 \
#   | sed -n "s#Primary key fingerprint: \(.*\)#\1#p")" \
#  && if [ -z "${FINGERPRINT}" ]; then echo "Warning! Invalid GPG signature!" && exit 1; fi \
#  && if [ "${FINGERPRINT}" != "${GPG_FINGERPRINT}" ]; then echo "Warning! Wrong GPG fingerprint!" && exit 1; fi \
#  && echo "All seems good, now unpacking nsd-${NSD_VERSION}.tar.gz..." \
#  && tar xzf nsd-${NSD_VERSION}.tar.gz && cd nsd-${NSD_VERSION} \
#  && ./configure \
#     CFLAGS="-O2 -flto -fPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security" \
#     LDFLAGS="-Wl,-z,now -Wl,-z,relro" \
#  && make && make install \
#  && apk del build-dependencies \
#  && rm -rf /var/cache/apk/* /tmp/* /root/.gnupg

# COPY keygen /usr/local/bin/keygen
# COPY signzone /usr/local/bin/signzone
# COPY ds-records /usr/local/bin/ds-records
# COPY run.sh /usr/local/bin/run.sh

# RUN chmod +x /usr/local/bin/*

VOLUME /zones /etc/nsd /var/db/nsd

EXPOSE 53 53/udp

CMD ["run.sh"]
