FROM ${NS_REMOTE}/dns-centos-systemd:${VERSION}.${CONTAINER_BRANCH}

MAINTAINER Operations at Ribose <operations@ribose.com>

LABEL description "Simple DNS authoritative server with DNSSEC support" \
      maintainer="Hardware <contact@meshup.net>"

ARG NSD_VERSION=4.1.17

# https://pgp.mit.edu/pks/lookup?search=0x7E045F8D&fingerprint=on&op=index
# pub  4096R/7E045F8D 2011-04-21 W.C.A. Wijngaards <wouter@nlnetlabs.nl>
ARG GPG_SHORTID="0x7E045F8D"
ARG GPG_FINGERPRINT="EDFA A3F2 CA4E 6EB0 5681  AF8E 9F6F 1C2D 7E04 5F8D"
ARG SHA256_HASH="107fa506d18ed6fd0a922d1b96774afd9270ec38ec6b17cd7c46fb9433a03a6c"

ENV UID=991 GID=991
RUN yum install -y epel-release
RUN yum install -y openssl nsd

# Run the setup script to create self signed certificates for controlling NSD (iff the nsd-control support is enabled) and for the server itself.
RUN nsd-control-setup

# Start the service.
RUN systemctl enable nsd
# RUN systemctl start nsd

# COPY keygen /usr/local/bin/keygen
# COPY signzone /usr/local/bin/signzone
# COPY ds-records /usr/local/bin/ds-records
# COPY run.sh /usr/local/bin/run.sh

# RUN chmod +x /usr/local/bin/*

VOLUME /zones /etc/nsd /var/db/nsd

EXPOSE 53 53/udp

CMD ["run.sh"]
