FROM ${NS_REMOTE}/dns-centos-systemd:${VERSION}.${CONTAINER_BRANCH}

MAINTAINER Operations at Ribose <operations@ribose.com>

LABEL description "Development container for NSD fuzzing project" \
      maintainer="Operations at Ribose <operations@ribose.com>"

ARG NSD_VERSION=4.1.17
ARG SHA256_HASH="107fa506d18ed6fd0a922d1b96774afd9270ec38ec6b17cd7c46fb9433a03a6c"
ARG GPG_SHORTID="0x7E045F8D"
ARG GPG_FINGERPRINT="EDFA A3F2 CA4E 6EB0 5681  AF8E 9F6F 1C2D 7E04 5F8D"


#Install dev tools
#RUN yum group install -y "Development Tools"
RUN yum install -y gcc openssl openssl-devel libevent-devel wget net-tools

#Build nsd
RUN mkdir -p /etc/nsd/src && cd /etc/nsd/src \
	&& wget -q https://www.nlnetlabs.nl/downloads/nsd/nsd-${NSD_VERSION}.tar.gz \
	&& wget -q https://www.nlnetlabs.nl/downloads/nsd/nsd-4.1.17.tar.gz.asc \
	&& echo "Verifying both integrity and authenticity of nsd-${NSD_VERSION}.tar.gz..." \
	&& CHECKSUM=$(sha256sum nsd-${NSD_VERSION}.tar.gz | awk '{print $1}') \
	&& if [ "${CHECKSUM}" != "${SHA256_HASH}" ]; then echo "Warning! Checksum does not match!" && exit 1; fi \
	&& gpg --keyserver keys.gnupg.net --recv-keys ${GPG_SHORTID} \
	&& FINGERPRINT="$(LANG=C gpg --verify nsd-${NSD_VERSION}.tar.gz.asc nsd-${NSD_VERSION}.tar.gz 2>&1 \
	| sed -n "s#Primary key fingerprint: \(.*\)#\1#p")" \
	&& if [ -z "${FINGERPRINT}" ]; then echo "Warning! Invalid GPG signature!" && exit 1; fi \
	&& if [ "${FINGERPRINT}" != "${GPG_FINGERPRINT}" ]; then echo "Warning! Wrong GPG fingerprint!" && exit 1; fi \
	&& echo "All seems good, now unpacking nsd-${NSD_VERSION}.tar.gz..." \
	&& tar xzf nsd-${NSD_VERSION}.tar.gz && cd nsd-${NSD_VERSION} \
	&& ./configure \
	&& make \
	&& make install \
	&& make clean

#Remove unused deps
RUN yum -y autoremove 

#May be omitted if we want to make a minimal configuration
RUN nsd-control-setup

#TODO: Check if needed
VOLUME /zones /etc/nsd /var/db/nsd

EXPOSE 53 53/udp

CMD ["run.sh"]
